### ISSUE TITLE
Get hyperlinks from a PDF

### ISSUE THREAD

**Issue by larytet** [maxpmaxp/pdfreader#43]
Hi,

I have a simple PDF,  https://github.com/larytet/YALAS/releases/download/12/my-link.pdf, containing a hyperlink. My goal is to get the reference and the link text.

    fd = open("my-link.pdf", "rb")
    viewer = pdfreader.SimplePDFViewer(fd)
    viewer.navigate(1)
    viewer.render()
    viewer.canvas.strings  # I get correct text "MyLink Text"
    viewer.canvas.text_content # Encoded (raw) representation of "MyLink Text" ?
    viewer.stream # I get b'0.1 w\nq 0 0 612 792 re\nW* n\n .... 
    viewer.resources.XObject # Empty dictionary {}

How do I get the reference itself http://mylink.com ?
Thanks

**Comment by maxpmaxp** [comment]
@larytet According to PDF specification hypertext links are not a part of page content, they are annotations (see [12.5 Annotations](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=389), which help user to interact with a document. That's why you should access it through document structure, rather than document view.

Annotations can be defined in `Page` objects and accessible through document `Catalog` which is `SimplePDFViewer.doc.root`. URL annotations have subtype of `Link`.

Here is the code:

```
>>> import pdfreader
>>> fd = open("my-link.pdf", "rb")
>>> viewer = pdfreader.SimplePDFViewer(fd)
>>> first_page = viewer.doc.root.Pages.Kids[0]
>>> links = [annot.A.URI for annot in first_page.Annots if annot.Subtype == 'Link']
>>> links
[b'http://mylink.com/']
```

I'm going to add a section about links to the project docs.
